# Generated by Django 4.2.7 on 2024-02-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar_alter_user_city_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('editor', 'editor'), ('member', 'member')], default='member', verbose_name='Роль пользователя'),
        ),
    ]
